import Link from "next/link";
import {
  CONTACT_EMAIL,
  OPERATOR_COUNTRY,
  OPERATOR_NAME,
} from "./contact";
import type { LegalDoc } from "./types";

/**
 * Written against what the code actually does, not against a template. Every
 * processor named here appears in the source; every data category maps to a
 * column in supabase/migrations/schema.sql.
 *
 * If you change what the app collects or who it sends data to, this file is
 * part of that change. In particular:
 *  - new third-party API   → add it to "Who we share it with"
 *  - new table or column   → add it to "What we collect"
 *  - new inference or score → add it to "What we work out about you"
 *
 * Section ids are public URLs. People link to specific clauses; don't rename
 * them casually.
 */
export const PRIVACY: LegalDoc = {
  slug: "privacy",
  title: "Privacy Policy",
  shortTitle: "Privacy",
  updated: "2026-02-05",

  intro: (
    <>
      <p>
        Your creative journey is <em>personal</em> — so is the data behind it.
        This policy explains what Meraki collects, why, who else sees it, how
        long it&apos;s kept, and what you can do about all of that.
      </p>
      <p>
        <strong>The short version:</strong> we don&apos;t sell your data, we
        don&apos;t run analytics or advertising trackers, and we don&apos;t
        build a profile of you for anyone else&apos;s benefit. What we collect
        exists to make the app work for you, and you can export or delete it at
        any time.
      </p>
      <p>
        This policy should be read alongside our{" "}
        <Link href="/terms">Terms of Service</Link>.
      </p>
    </>
  ),

  sections: [
    {
      id: "who-we-are",
      title: "Who We Are",
      body: (
        <>
          <p>
            Meraki is operated by <strong>{OPERATOR_NAME}</strong>, an
            individual based in {OPERATOR_COUNTRY}. There is no company behind
            it — it is a personal project, run and paid for by one person.
          </p>
          <p>
            For the purposes of data protection law, {OPERATOR_NAME} is the{" "}
            <strong>data controller</strong>: the person who decides what
            personal data is collected and why. You can reach the controller at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
          <p>
            Meraki is offered free of charge. We may change or discontinue it —
            see <a href="#retention">How Long We Keep Your Data</a> for what
            happens to your data if the service closes.
          </p>
        </>
      ),
    },
    {
      id: "what-we-collect",
      title: "What We Collect",
      body: (
        <>
          <h3>Information you give us</h3>
          <ul>
            <li>
              <strong>Account:</strong> your email address and full name. If you
              register with a password, it is hashed by Supabase and we never
              see it in plain text. If you sign in with Google, we receive your
              email, name, and profile photo.
            </li>
            <li>
              <strong>Profile:</strong> a bio, a location you type in, and an
              avatar image, all optional.
            </li>
            <li>
              <strong>Quiz answers:</strong> your responses about available time,
              creative preferences, and lifestyle.
            </li>
            <li>
              <strong>Practice sessions:</strong> the hobby, session type,
              duration, <strong>how you were feeling</strong> (your mood), free-text
              notes, and any photo you attach.
            </li>
            <li>
              <strong>Hobbies and challenges:</strong> which you have chosen,
              their status, and when you started or completed them.
            </li>
          </ul>
          <p>
            Your notes and mood entries are the most personal thing in the app.
            Please treat the notes field as a private journal, not a form —
            there is no need to record health information, and we ask that you
            don&apos;t.
          </p>

          <h3>What we work out about you</h3>
          <p>
            Some of what we hold is generated by Meraki rather than typed by you.
            It is still information about you, and all of it is covered by the
            rights below.
          </p>
          <ul>
            <li>
              <strong>Hobby matches:</strong> a match percentage, tags, and a
              written explanation of why a hobby suits you, derived from your
              quiz answers.
            </li>
            <li>
              <strong>AI feedback:</strong> observations, suggested areas of
              growth, and encouragement generated from the notes you write about
              a practice session.
            </li>
            <li>
              <strong>Progress:</strong> streaks, milestones earned, and
              aggregate session statistics.
            </li>
          </ul>

          <h3>Information collected automatically</h3>
          <p>
            Very little, and none of it for analytics. We keep short-lived
            records of background jobs — the hobby-matching run, for example —
            so the app can report progress and recover if you refresh the page.
            Our hosting providers keep standard server logs, which include IP
            addresses, for security and troubleshooting.
          </p>

          <h3>What we don&apos;t collect</h3>
          <p>
            Meraki runs <strong>no analytics</strong>, no advertising or
            tracking cookies, no pixels, no session recording, and no
            cross-site tracking. We do not buy data about you from anyone, and
            we do not enrich your profile from outside sources. The only cookie
            we set is the one that keeps you signed in.
          </p>
        </>
      ),
    },
    {
      id: "location",
      title: "Location",
      body: (
        <>
          <p>
            Meraki only uses location when you ask it to. If you use{" "}
            <strong>Find Nearby</strong> to look for local workshops and
            classes, we take the location you provide — either typed in, or from
            your browser if you grant permission — and send it to Google Places
            to run the search.
          </p>
          <p>
            We save the results against that search so we don&apos;t have to
            repeat it every time you look. We do not track your location in the
            background, we do not build a location history, and we do not use
            location for anything other than that search.
          </p>
        </>
      ),
    },
    {
      id: "why-and-legal-basis",
      title: "Why We Use It, and on What Basis",
      body: (
        <>
          <p>
            Data protection law asks us to name a lawful reason for each use.
            Ours are:
          </p>

          <h3>To provide the service you asked for</h3>
          <p>
            Creating and securing your account, matching you with hobbies from
            your quiz answers, generating challenges and practice feedback,
            recording sessions, and calculating streaks and milestones.{" "}
            <em>Basis: performance of a contract with you</em> — this is the
            service you signed up for, and without this data there is nothing to
            provide.
          </p>

          <h3>To keep the service working and secure</h3>
          <p>
            Diagnosing faults, preventing abuse, and protecting accounts.{" "}
            <em>Basis: our legitimate interests</em> in running a functioning,
            non-abused service, balanced against your interests.
          </p>

          <h3>To meet legal obligations</h3>
          <p>
            Responding to valid legal requests and to your own rights requests.{" "}
            <em>Basis: compliance with a legal obligation.</em>
          </p>

          <p>
            We do not use your data for advertising, we do not sell or rent it,
            and we do not share it for anyone else&apos;s marketing.
          </p>
        </>
      ),
    },
    {
      id: "who-we-share-with",
      title: "Who We Share It With",
      body: (
        <>
          <p>
            We share data with the services that make Meraki work, and with
            nobody else. This is the complete list.
          </p>
          <ul>
            <li>
              <strong>Supabase</strong> — hosts the database, file storage, and
              authentication. It holds everything described above. Supabase
              processes this data on our instructions.{" "}
              <a
                href="https://supabase.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy policy
              </a>
              .
            </li>
            <li>
              <strong>OpenAI</strong> — powers hobby matching, challenge
              generation, and practice feedback. Your{" "}
              <strong>quiz answers</strong> and the{" "}
              <strong>notes you write about practice sessions</strong> are sent
              to OpenAI to generate these. Please keep that in mind when writing
              notes.{" "}
              <a
                href="https://openai.com/policies/privacy-policy/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy policy
              </a>
              .
            </li>
            <li>
              <strong>Opik (Comet)</strong> — records how our AI features
              perform so we can spot failures and improve results. Because it
              monitors the AI itself, these records{" "}
              <strong>can include the text sent to and returned from the
              model</strong> — which means your quiz answers and session notes.{" "}
              <a
                href="https://www.comet.com/site/privacy-policy/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy policy
              </a>
              .
            </li>
            <li>
              <strong>Google Sign-In</strong> — if you choose it, we receive
              your email, name, and profile photo. We never access your Gmail,
              Drive, or any other Google data.{" "}
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy policy
              </a>
              .
            </li>
            <li>
              <strong>Google Maps and Places</strong> — runs the{" "}
              <strong>Find Nearby</strong> search. It receives the location you
              searched for. See <a href="#location">Location</a> above.
            </li>
            <li>
              <strong>YouTube (YouTube API Services)</strong> — Meraki uses the
              YouTube API to find videos for the hobbies you explore. Your use
              of those features is also subject to the{" "}
              <a
                href="https://www.youtube.com/t/terms"
                target="_blank"
                rel="noopener noreferrer"
              >
                YouTube Terms of Service
              </a>{" "}
              and{" "}
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google&apos;s Privacy Policy
              </a>
              . You can review and revoke Meraki&apos;s access to your data via
              the{" "}
              <a
                href="https://myaccount.google.com/permissions"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google security settings page
              </a>
              .
            </li>
          </ul>
          <p>
            We may also disclose data if we are legally required to, or where it
            is necessary to establish, exercise, or defend a legal claim. If
            that ever happens and we are permitted to tell you, we will.
          </p>
        </>
      ),
    },
    {
      id: "transfers",
      title: "Where Your Data Is Stored",
      body: (
        <>
          <p>
            Meraki is operated from {OPERATOR_COUNTRY}, and the services listed
            above are operated from other countries — principally the United
            States and the European Union. Using Meraki therefore involves
            transferring your data internationally.
          </p>
          <p>
            Where data protection law requires a safeguard for those transfers,
            we rely on the terms offered by each provider, which include
            standard contractual clauses. If you would like to know where a
            specific piece of your data is held, ask us and we will tell you.
          </p>
        </>
      ),
    },
    {
      id: "retention",
      title: "How Long We Keep Your Data",
      body: (
        <>
          <ul>
            <li>
              <strong>Account, profile, and everything you create</strong> — for
              as long as your account exists.
            </li>
            <li>
              <strong>If you delete your activity data</strong> — removed
              immediately, and your account remains.
            </li>
            <li>
              <strong>If you delete your account</strong> — your profile,
              sessions, notes, photos, quiz answers, matches, and login are all
              removed immediately. This is not a soft delete and it cannot be
              undone.
            </li>
            <li>
              <strong>Background job records</strong> — short-lived, kept only
              while the job runs and briefly afterwards.
            </li>
            <li>
              <strong>Server logs held by our providers</strong> — retained
              according to each provider&apos;s own schedule, which we do not
              control.
            </li>
          </ul>
          <p>
            Copies may persist for a limited period in provider backups before
            being overwritten. Data already sent to OpenAI or Opik is subject to
            their retention schedules, which we do not control.
          </p>
          <p>
            <strong>If Meraki shuts down:</strong> this is a personal project
            and it may not run forever. If we decide to close it, we will give
            you notice by email before it happens, so you have time to export
            your data, and we will delete the database afterwards.
          </p>
        </>
      ),
    },
    {
      id: "your-rights",
      title: "Your Rights",
      body: (
        <>
          <p>
            These rights apply to everyone who uses Meraki, wherever you live.
            We don&apos;t think it makes sense to give people different rights
            depending on their address.
          </p>
          <ul>
            <li>
              <strong>Access and export</strong> — see everything through
              Profile and Settings, or download a copy of your data from{" "}
              <strong>Settings → Export My Data</strong>. The file is JSON and
              includes your account details, profile, sessions, notes, quiz
              answers, matches and progress. Photos are included as links rather
              than files, so download any you want to keep{" "}
              <em>before</em> deleting your account.
            </li>
            <li>
              <strong>Correct</strong> — update your profile at any time.
            </li>
            <li>
              <strong>Delete</strong> — from Settings, either wipe your activity
              data and keep the account, or delete the account entirely. Both
              take effect immediately.
            </li>
            <li>
              <strong>Object or restrict</strong> — ask us to stop or limit a
              particular use of your data.
            </li>
            <li>
              <strong>Portability</strong> — the export is machine-readable, so
              you can take it elsewhere.
            </li>
            <li>
              <strong>Complain</strong> — you can lodge a complaint with a data
              protection authority. In {OPERATOR_COUNTRY} that is the{" "}
              <em>Instance Nationale de Protection des Données Personnelles</em>{" "}
              (INPDP). If you are in the EU or the UK, you may complain to your
              national supervisory authority instead.
            </li>
          </ul>
          <p>
            Most of these you can do yourself in the app. For anything else,
            email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> and we
            will respond within <strong>30 days</strong>. We may need to check
            that the request is genuinely from you before acting on it.
          </p>
        </>
      ),
    },
    {
      id: "nobody-else-sees-it",
      title: "Nobody Else Can See Your Account",
      body: (
        <>
          <p>
            Meraki has no social features. There are no public profiles, no
            feeds, no followers, and no way for one user to look up another.
            Everything in your account is visible only to you.
          </p>
          <p>
            This is enforced by the database, not just the interface: access
            rules scope every row to the account that owns it, so another
            signed-in user cannot read your profile, sessions, notes, or photos
            even indirectly.
          </p>
          <p>
            If we ever add a way to share something publicly, it will be
            off by default and we will ask you before anything of yours becomes
            visible.
          </p>
        </>
      ),
    },
    {
      id: "automated-decisions",
      title: "Automated Decisions",
      body: (
        <>
          <p>
            Hobby matching is automated: a model reads your quiz answers and
            produces suggestions with a match percentage and an explanation. AI
            feedback on your sessions is generated the same way.
          </p>
          <p>
            These are suggestions, not decisions about you. They have no legal
            or similarly significant effect — nothing is granted or denied to
            you on their basis, and you can ignore them, retake the quiz, or
            choose any hobby you like regardless of what the matching says. If
            you would like a person to look at a result, ask us.
          </p>
        </>
      ),
    },
    {
      id: "cookies",
      title: "Cookies",
      body: (
        <p>
          We use exactly one cookie: the one that keeps you signed in. It is
          strictly necessary for the service to work, which is why there is no
          cookie banner asking you to accept it. No analytics cookies, no
          advertising cookies, no preference cookies, no third-party trackers.
        </p>
      ),
    },
    {
      id: "security",
      title: "Security",
      body: (
        <>
          <p>
            Your data is encrypted in transit (HTTPS/TLS) and at rest. Passwords
            are hashed, never stored in readable form. Database access is
            governed by row-level security, so records are scoped to the account
            that owns them, and uploaded photos sit behind the same per-user
            controls.
          </p>
          <p>
            No system is perfectly secure, and we will not pretend otherwise. If
            a breach affects your personal data and puts you at risk, we will
            tell you and notify the relevant authority, as the law requires. If
            you find a vulnerability, please report it to{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> — we will not
            pursue anyone who reports a genuine issue in good faith.
          </p>
        </>
      ),
    },
    {
      id: "children",
      title: "Children",
      body: (
        <>
          <p>
            Meraki is not designed or intended for children under 13, and we do
            not knowingly collect their data — see{" "}
            <Link href="/terms#eligibility">Who Can Use It</Link> for the age
            rule that governs your account.
          </p>
          <p>
            If you believe a child under 13 has given us personal information,
            email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> and we
            will delete it promptly.
          </p>
        </>
      ),
    },
    {
      id: "changes",
      title: "Changes to This Policy",
      body: (
        <p>
          If we change this policy we will update the date at the top. If a
          change materially affects how we use your data, we will tell you by
          email or in the app before it takes effect, so you can decide whether
          to keep using Meraki.
        </p>
      ),
    },
  ],

  contact: {
    heading: "Still have questions?",
    body: (
      <>
        Your creative journey is personal, and we respect that. If you ever have
        a concern about your data — or just want to know what we hold —
        we&apos;re here to listen.
      </>
    ),
  },
};
