-- Roadmap definitions (generated by AI)
create table public.roadmaps (
  id uuid primary key default gen_random_uuid(),
  hobby_id uuid references public.hobbies(id) on delete cascade not null,
  title text not null default '',
  description text not null default '',
  phases jsonb not null default '[]',
  total_phases int not null default 0,
  created_at timestamptz default now()
);

-- User's active roadmap per hobby
create table public.user_roadmaps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  roadmap_id uuid references public.roadmaps(id) on delete cascade not null,
  hobby_slug text not null default '',
  current_phase int not null default 0,
  started_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, roadmap_id)
);

-- Indexes
create index idx_user_roadmaps_user on public.user_roadmaps(user_id);

-- RLS
alter table public.roadmaps enable row level security;
alter table public.user_roadmaps enable row level security;

create policy "Authenticated users can read roadmaps"
  on public.roadmaps for select to authenticated using (true);

create policy "Users can read own user_roadmaps"
  on public.user_roadmaps for select to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own user_roadmaps"
  on public.user_roadmaps for insert to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own user_roadmaps"
  on public.user_roadmaps for update to authenticated
  using (auth.uid() = user_id);
